name: Build Windows executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash

    - name: Install PyInstaller
      run: |
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile bot.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-executable
        path: dist/*
